### ISSUE TITLE
Add 2 new bookmarklets

### ISSUE THREAD

**Issue by sylvxa** [Krazete/bookmarklets#17]
I've coded 2 bookmarklets that I believe users may want:

**Inspector** - Simple Inspect Element clone meant for users who don't have access to it.
[Repo](https://github.com/Silasssssss/Inspector)

**AutoClicker** - An AutoClicker that works on Chromebook and most simple sites (like Cookie Clicker)
[Repo](https://github.com/Silasssssss/bookmark-autoclicker)

**Comment by Krazete** [comment]
Sorry, but this repo is only for my own bookmarklets. I've updated the description and readme to emphasize this.
