### ISSUE TITLE
not loading.

### ISSUE THREAD

**Issue by willbioyes** [Krazete/bookmarklets#20]
when the javascript is tapped in the bookmarkelts bar it says this: 

![Screenshot 2022-09-19 6 07 28 PM](https://user-images.githubusercontent.com/113559070/191128331-6d8c6d47-0042-4db0-a31f-4f59a4b4f820.png)

do you know how to fix this?

**Comment by Krazete** [comment]
You didn't save the file on your computer and then add that local file as a bookmarklet, did you?
Edit your bookmarklet and check the URL. It should start with `javascript:`, not `file:`.

**Comment by Krazete** [comment]
And if that's not the issue, then try disabling your browser extensions.
Idk why it would be that, but a bunch of Google search results of "ERR_FILE_NOT_FOUND" blame extensions for this error.
